### PR TITLE
Adding CI tests

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [x] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Adding CI tests for orion. They will be triggered against each PR and will help us catch issues early.

## Related Tickets & Documents
- Closes # https://github.com/cloud-bulldozer/orion/issues/51

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.

## Testing
Tested in local. Attempting to test it from the PR as well.

### CODE REVIEW

**Comment by vishnuchalla** [comment]
@jtaleric @shashank-boyapally @paigerube14 PTAL 👋🏼 . All the payloads are working. We can add/update more scenarios in the follow up PRs if needed.

**Comment by vishnuchalla** [comment]
While cutting the release for this change, we need to make sure that appropriate ENVs are populated in prow that fit in with the updated configs.

**Review by shashank-boyapally — APPROVED** [review]

**Review by jtaleric — APPROVED** [review]
lgtm! Thanks!

**Pull request merged**
